### ISSUE TITLE
Option to move dock to top

### ISSUE THREAD

**Issue by MartinPL** [fthx/dock-from-dash#1]
Not sure if this is in scope of this project, but this is my first thing with I want to do with dock.

**Comment by fthx** [comment]
No you're right, that's not consistent with GS layout.

BUT you have a surprise here:
https://github.com/fthx/dock-from-dash
;-)

I find it not that much pleasant but that's just my opinion. But it works!

I leave this issue open to see if some people ask for this.

**Comment by fthx** [comment]
Please note I will not update both extensions.
;-)

There are some useful commits now that are not included in top-one.

**Comment by fthx** [comment]
So I did it.
This one is up-to-date.
https://github.com/fthx/dash-from-panel

**Comment by fthx** [comment]
Could you tell me if the panel hovering is ok or if I have to recreate a smaller barrier to reveal the dock.

**Comment by MartinPL** [comment]
Barrier would be nice so it will appears after litt push to top edge.
