### ISSUE TITLE
Add a configuration panel to change times

### ISSUE THREAD

**Issue by frandieguez** [fthx/dock-from-dash#10]
Hi!
 
first of all thanks for this simple but effective extension. Something that annoys me when using it is that I want the dash to be revealed quicker. After see your code I think that values below are those that I want to be configurable.

```
var DASH_MAX_HEIGHT_RATIO = 0.15;
var DASH_OPACITY_RATIO = 0.9;
var SHOW_DOCK_BOX_HEIGHT = 2;
var SHOW_DOCK_DURATION = 200;
var HIDE_DOCK_DURATION = 200;
var SHOW_DOCK_DELAY = 200;
var HIDE_DOCK_DELAY = 500;
var AUTO_HIDE_DOCK_DELAY = 500;
```

I think that a panel to change these values from an UI would be incredible.

**Comment by fthx** [comment]
For this one, my first wish is to have a simply-works extension.
So, could we look at what duration or other settings (that I pushed in headers to be easily hackable) we should change?
Could you copy me your favorite DfD settings?

**Comment by frandieguez** [comment]
Let me test different values and I will come back with my preferences.

**Comment by fthx** [comment]
Great. We have to balance:
var SHOW_DOCK_DURATION = 200;
and
var SHOW_DOCK_DELAY = 200;

The second one is set to simulate a pressure without heavy code and the first one is obviously the animation time.
I agree that at the moment it's somewhat slow.

**Comment by frandieguez** [comment]
Here are my desired values.
`
var SHOW_DOCK_DURATION = 100;
var HIDE_DOCK_DURATION = 200;
var SHOW_DOCK_DELAY = 50;
var HIDE_DOCK_DELAY = 200;
var AUTO_HIDE_DOCK_DELAY = 200;`

As you can see I want quick show/hide times, so the dock doesn't interfere with my viewport. I know that this kind of configuration doesn't work well for everyone.

If I develop the settings panel for your extension, would you willing to merge it?

**Comment by fthx** [comment]
Ok, I tried yours and found a reasonable compromise, I think!
https://github.com/fthx/dock-from-dash/commit/dcb4efb5e6c599d9d4f07957a2533e10d575634c

I feel that's not a good idea here to make a pref panel. Because there will be times, ok, but then some users will ask for this and this and this... and that's clearly not the goal of this dock, that I would like to keep very different from Dash to Dock.

**Comment by frandieguez** [comment]
Awesome, update to v20 and now it fits my requirements. Thanks again for this simple but efective extension.
