### ISSUE TITLE
Isolated Background Icons

### ISSUE THREAD

**Issue by avantbored** [fthx/dock-from-dash#100]
Hello, 

The backgrounds of icons on the dash are tiled and disconnected, rather than unified by a single background. 

Running Gnome 46 on Eondeavour OS. 

![Screenshot from 2024-04-22 08-17-20](https://github.com/fthx/dock-from-dash/assets/31809538/788c587f-951b-4fc5-b9bf-d678c3247964)

**Comment by fthx** [comment]
I don't get this, running Ubuntu GS 46.
The extension uses native GS dash object.

I think it's a theme bug?
