### ISSUE TITLE
Dock does not appear

### ISSUE THREAD

**Issue by Neo-29** [fthx/dock-from-dash#105]
I installed the extension, hoping to get a dock ....Nothing.
Im on G47 arch wayland
Any explanation or tip?

**Comment by fthx** [comment]
Nothing more than here:
https://extensions.gnome.org/extension/4703/dock-from-dash/

The dock is not displayed even if no window overlaps. Just appearing on bottom hover.

**Comment by Neo-29** [comment]
> Nothing more than here: https://extensions.gnome.org/extension/4703/dock-from-dash/
> 
> The dock is not displayed even if no window overlaps. Just appearing on bottom hover.

Nothing appears in any circumstances....
I don't get it

**Comment by fthx** [comment]
I tested this on Ubuntu 24.10 GS 47 and everything seems ok (+ no errors il logs).
Is there any error in logs ("JS") ?

**Comment by fthx** [comment]
Do you have some other extensions installed?
If so, please list them.

**Comment by Neo-29** [comment]
> I tested this on Ubuntu 24.10 GS 47 and everything seems ok (+ no errors in logs). Is there any error in logs ("JS") ?

```sept. 22 14:57:13 neo29 gnome-shell[1148]: st_widget_get_theme_node called on the widget [0x5c64064a8390 Gjs_dock-from-dash_fthx_extension_Dock:insensitive "dash"] which is not in the stage.
sept. 22 14:57:13 neo29 gnome-shell[1148]: Spurious clutter_actor_allocate called for actor 0x5c64064a8390/dash [Gjs_dock-from-dash_fthx_extension_Dock] which isn't a descendent of the stage!
sept. 22 14:57:26 neo29 gnome-shell[1148]: st_widget_get_theme_node called on the widget [0x5c64063d8b30 Gjs_dock-from-dash_fthx_extension_Dock:insensitive "dash"] which is not in the stage.
sept. 22 14:57:26 neo29 gnome-shell[1148]: Spurious clutter_actor_allocate called for actor 0x5c64063d8b30/dash [Gjs_dock-from-dash_fthx_extension_Dock] which isn't a descendent of the stage!
sept. 22 14:58:02 neo29 gnome-shell[1148]: st_widget_get_theme_node called on the widget [0x5c640119c440 Gjs_dock-from-dash_fthx_extension_Dock:insensitive "dash"] which is not in the stage.
sept. 22 14:58:02 neo29 gnome-shell[1148]: Spurious clutter_actor_allocate called for actor 0x5c640119c440/dash [Gjs_dock-from-dash_fthx_extension_Dock] which isn't a descendent of the stage!
-- Boot 350dc81de60a4bd1b26c77b517349e08 --
-- Boot 01500719853d426c8f88d6384dc2a46f --
sept. 22 18:39:00 neo29 gnome-shell[5144]:   inflating: /home/neo29/.local/share/gnome-shell/extensions/dock-from-dash@fthx/extension.js
sept. 22 18:39:00 neo29 gnome-shell[5144]:  extracting: /home/neo29/.local/share/gnome-shell/extensions/dock-from-dash@fthx/metadata.json
sept. 22 18:48:13 neo29 gnome-shell[1157]: st_widget_get_theme_node called on the widget [0x58b28c53a8c0 Gjs_dock-from-dash_fthx_extension_Dock:insensitive "dash"] which is not in the stage.
sept. 22 18:48:13 neo29 gnome-shell[1157]: Spurious clutter_actor_allocate called for actor 0x58b28c53a8c0/dash [Gjs_dock-from-dash_fthx_extension_Dock] which isn't a descendent of the stage!
```

**Comment by Neo-29** [comment]
> Do you have some other extensions installed? If so, please list them.

```arch-update@RaphaelRochet
openweather-extension@penguin-teal.github.io
blur-my-shell@aunetx
batterytime@typeof.pw
CoverflowAltTab@palatis.blogspot.com
just-perfection-desktop@just-perfection
appindicatorsupport@rgcjonas.gmail.com
Vitals@CoreCoding.com
AlphabeticalAppGrid@stuarthayhurst
just-another-search-bar@xelad0m
top-bar-organizer@julian.gse.jsts.xyz
clipboard-history@alexsaveau.dev
compiz-alike-magic-lamp-effect@hermes83.github.com
quick-settings-audio-panel@rayzeq.github.io
caffeine@patapon.info
drive-menu@gnome-shell-extensions.gcampax.github.com
light-style@gnome-shell-extensions.gcampax.github.com
legacyschemeautoswitcher@joshimukul29.gmail.com
gestureImprovements@gestures
desktop-cube@schneegans.github.com
custom-hot-corners-extended@G-dH.github.com
openbar@neuromorph
forge@jmmaranan.com
unite@hardpixel.eu
dock-from-dash@fthx```

**Comment by fthx** [comment]
Ok there are possibly some conflicts.
Could you use only dock from dash to see if it's ok?
If not I suggest to begin with custom hot corners one.

**Comment by fthx** [comment]
Did you use such a huge extensions setup before (GS 46 ?), with dock from dash running?

**Comment by Neo-29** [comment]
I tried on manjaro with no extension enabled.
The dock does not appear in any circonstances.
I'm on laptops.

**Comment by fthx** [comment]
That's odd.
I just tried on my laptop without any screen connected after a cold restart and it works.

To be 100% sure: you go with your mouse cursor at the bottom of your screen and the dock does not appear?

Could you check in GNOME's Logs app the messages related to this extension and paste here the detailed results (with call stack, when you click on the message)?

**Comment by Neo-29** [comment]
`To be 100% sure: you go with your mouse cursor at the bottom of your screen and the dock does not appear?`
Yes
`Could you check in GNOME's Logs app the messages related to this extension and paste here the detailed results (with call stack, when you click on the message)?`
Which message?

**Comment by fthx** [comment]
Those ones.
https://github.com/fthx/dock-from-dash/issues/105#issuecomment-2366869278

**Comment by Neo-29** [comment]
> Ok there are possibly some conflicts. Could you use only dock from dash to see if it's ok? If not I suggest to begin with custom hot corners one.
Here ... this is it
In that case the pb is Custom hot corner extended breaking the apparition of the dock

Unfortunately I REALLY need it in my workflow


Is the a workaround?
