### ISSUE TITLE
Conflict with `Custom Hot Corners-Extended`

### ISSUE THREAD

**Issue by Neo-29** [fthx/dock-from-dash#106]
The extension does not work with https://github.com/G-dH/custom-hot-corners-extended

Cool if a fix could be found.

Tks a lot for your work

**Comment by fthx** [comment]
DFD does create a GS hot corner (bottom edge).
So I really cannot act on another extension that does hack/remove/... this hot corner.

**Comment by Neo-29** [comment]
> DFD does create a GS hot corner (bottom edge). So I really cannot act on another extension that does hack/remove/... this hot corner.

I asked on the other side.
Maybe have the possibility of disabling the bottom corners... I'll leave the suggestion

**Comment by fthx** [comment]
I did not look at the edges extension. But probably it does add and update hot corners so the side effect is removing my hot corner. So the other extension could take care of existing non-GS hot corners but that's maybe some painful work.

**Comment by Neo-29** [comment]
> I did not look at the edges extension. But probably it does add and update hot corners so the side effect is removing my hot corner. So the other extension could take care of existing non-GS hot corners but that's maybe some painful work.

https://github.com/G-dH/custom-hot-corners-extended/issues/110#issuecomment-2380589106

**Comment by Neo-29** [comment]
@fthx
https://github.com/G-dH/custom-hot-corners-extended/issues/110#issuecomment-2380589106
