### ISSUE TITLE
When mouse pass fast through the dock icons the dock doesn't hide

### ISSUE THREAD

**Issue by marcelovbcfilho** [fthx/dock-from-dash#12]
## What happened

I downloaded the latest version available in Gnome Extensions of the extension and if I pass the mouse a little fast through the dock icons it won't go away and will display the tooltip of the program.

If you look at the image I used the CTRL + SHIFT + PrintScreen button, moved my mouse around to take the screenshot and the dock is still visible through this process which makes me believe that the dock for some reason didn't have triggered an on focus lost or some method like this.

I can help with debug info if the commands were provided.

![Screenshot from 2022-02-03 09-53-35](https://user-images.githubusercontent.com/51462138/152346939-d792f14f-6573-4d70-a8eb-635ce1d47eb4.png)

### Extension version

This were the version data available inside the metadata.json inside extensions folder.

```json
  "url": "https://github.com/fthx/dock-from-dash",
  "uuid": "dock-from-dash@fthx",
  "version": 20
```

**Comment by fthx** [comment]
Hi,

Could you tell me more precisely how you get that? I did not success to reproduce.

**Comment by marcelovbcfilho** [comment]
I recorded a video to illustrate and help to figure out the problem.

https://user-images.githubusercontent.com/51462138/152349733-46a2e86c-583c-41ac-b841-452d348becfd.mp4

Here are my system info if them can help.

![Screenshot from 2022-02-03 10-15-26](https://user-images.githubusercontent.com/51462138/152349950-52468601-f1bb-47f2-9cbb-b439ff932f64.png)

**Comment by fthx** [comment]
I will try to reproduce because it's fine tuning here.

**Comment by fthx** [comment]
I think this issue is solved by v28.
Reopen if needed, of course.
