### ISSUE TITLE
Add an option to have the dock always shown but only dodge active window / intellihide

### ISSUE THREAD

**Issue by DiamondBond** [fthx/dock-from-dash#15]
Would this be possible? or if not a feature that you could merge, then how should i go about editing extension.js to achieve this functionality locally?

**Comment by DiamondBond** [comment]
understandable, would there be any way to just send the dash to the back permanently then?
eg;
```
# Place panel at desktop-level
wmctrl -i -r $ID -b add,below
```

**Comment by fthx** [comment]
Should exist a solution with addChrome options but I did not look at this in this way, rather ensure the dock to be showed under all windows!  ;-)
I think you can hack the code easily to delete all the hiding stuff, just create and show the dock and go.
