### ISSUE TITLE
Dragging applicartion icon from dock doesn't open new instance 

### ISSUE THREAD

**Issue by seanleavy** [fthx/dock-from-dash#16]
The default Gnome overview dash behaviour is to open a new instance of an app when an app is dragged off the dock. Attached a video below.

Dock from dash doesn't mimic this behaviour. Not sure if that's by design or not so I'm logging this issue to check.

 *edit fixed video

https://user-images.githubusercontent.com/2906363/153458366-1659e654-a23f-4486-b262-775a8269dec4.mp4

**Comment by fthx** [comment]
Well, I see you're right. I've just tested without the only part of the code that modifies GS native objects (click) but that does not change anything.
Sorry but I cannot do anything here since I do use GS native dash as a dock.
