### ISSUE TITLE
Bug: Dock keeps showing for a long time

### ISSUE THREAD

**Issue by psydvl** [fthx/dock-from-dash#2]
If you fast move mouse through screen down edge, like down and up, dock appears and never disappears, until you move mouse down to edge again.
For now, it starts to irritate me.
Can you add something like countdown for disappearing or maybe another mouse detection?

**Comment by fthx** [comment]
https://github.com/fthx/dock-from-dash/commit/42324fd9a72a509536a023ca745729581cf21a7a

**Comment by fthx** [comment]
Feel free to reopen if needed.
