### ISSUE TITLE
Do that mouse wheel switches between workspaces

### ISSUE THREAD

**Issue by rastersoft** [fthx/dock-from-dash#23]
Dash-to-dock has a nice feature, which is that using the mouse wheel over the dock allows to switch between workspaces. It would be great if you could add that to dock-from-dash.

**Comment by fthx** [comment]
Thanks.
I was writing this when I saw your PR...
At least I could learn correctly how to do this!
I have a look on your PR and push it if it's (probably) better than mine.

**Comment by fthx** [comment]
FYI I did include this in my latest:
https://extensions.gnome.org/extension/5143/dashbar/
Just the dash in panel, in a real way ;-)
