### ISSUE TITLE
Yaru theme is not applied for the dock

### ISSUE THREAD

**Issue by fthx** [fthx/dock-from-dash#25]
It could be nice if Yaru styling could be applied on the dock, as the dash in overview.
@rastersoft ?

**Comment by fthx** [comment]
@Feichtmeier ?

**Comment by rastersoft** [comment]
Mmm... How can I apply the Yaru theme? Just to do a test...

**Comment by rastersoft** [comment]
Oh, ok... with gnome-tweaks :-)

**Comment by rastersoft** [comment]
I don't see difference between the dash and the dock after changing the theme to Yaru...

**Comment by rastersoft** [comment]
You are right :-D I like the original theme so I never changed it 😇

**Comment by fthx** [comment]
Since 22.04 it's the first time I do use Ubuntu session rather than GNOME session (with Adwaita).
Of course, one reason is new COLORS!

**Comment by fthx** [comment]
it does

**Comment by rastersoft** [comment]
It works now, yes. Anyway, I installed other themes (couldn't find where to download Yaru) and the theme is set to the dock... I'll test in a virtual machine with Ubuntu.

**Comment by fthx** [comment]
My bad, I realize that it's just a question of background... Yaru dash has a thin white border that I did not see!!
Oups.
