### ISSUE TITLE
Not hiding the dock after app launch

### ISSUE THREAD

**Issue by fthx** [fthx/dock-from-dash#26]
> BTW: now that this is implemented, what do you think about not hiding the dock after clicking on an icon to launch an app? Because I usually, at login, launch the mail client in the first workspace, switch to the next, launch firefox, switch to the next, and launch telegram, all in a row.

**Comment by fthx** [comment]
@rastersoft I don't understand the point here, the dock IS not hiding after a click.
Maybe you talk about a click in an app menu item?

**Comment by rastersoft** [comment]
Ok, the problem happens only when switching from one workspace into another... I'll try to fix it.

**Comment by rastersoft** [comment]
Sent a patch for this.
