### ISSUE TITLE
Minimize on click function

### ISSUE THREAD

**Issue by Brierith** [fthx/dock-from-dash#3]
The title says it all, I think it would be more useful if a functionality as such exist, and perhaps having one wouldn't go far from the design and principle of the stock shell dock who could have that function if it were a dock. Thank you for this great extension!

**Comment by fthx** [comment]
Yes that's a good and simple feature and close to GS native behavior.
I was thinking about this and your BR will make me try to handle this.

I'll do it if and only if GS native code allows me to hack dock items signals.

**Comment by fthx** [comment]
I tried and succeeded to make a signal on each dock app icon with a minimizing action but it interferes with this new GS dash instance behavior.
Minimizing is not reliable at all, I suspect the dash of the dock is refreshed or something else...

So I consider this is out of the scope of this extension. I want to keep it simple, with a simple and reliable code.

**Comment by fthx** [comment]
I realize that I did not mention that this feature is complete now.
I hacked the native GS click function in a reliable way.

**Comment by Brierith** [comment]
Hey that's great I thought you wouldn't continue pursuing it since it is already out of scope of this project, but you still did, thank you. I have another request  relevant to this behavior if you may, perhaps the **dock should not hide at the same time the minimize on click function is triggered**, in that way it allows the user to seamlessly minimize and return an app to desktop without going down to show the dock again every time an app is minimized. Thank you.

**Comment by Brierith** [comment]
or perhaps dock should not hide as long as the mouse is hovering over it?

**Comment by fthx** [comment]
The problem here is that the hover signal is not emitted correctly by GS.
If you open an app through its menu (or change app) then leaving the dock and menu, the (lost) hover signal is not emitted and GS thinks the dock is still hovered...
So I cannot check to not close the dock if it's still hovered because of false positive cases.

**Comment by fthx** [comment]
FYI it will be as you requested soon.
