### ISSUE TITLE
App icon hover states at bottom edge of screen

### ISSUE THREAD

**Issue by arthurflor23** [fthx/dock-from-dash#34]
Hi,
currently, the extension doesn't consider app hovering at the edge of the screen.
It's just a little, but it still doesn't catch the hover.

default gnome (hover state):
![Screenshot from 2022-04-01 08-42-03](https://user-images.githubusercontent.com/11759042/161257952-463b29dd-1b3d-4c2e-a23f-1e9c45550109.png)

with the extension (no hover):
![Screenshot from 2022-04-01 08-43-22](https://user-images.githubusercontent.com/11759042/161257987-d351edb3-a716-4a21-986c-1c440c04ffdb.png)

I think it's the same issue when gnome released version 40
https://gitlab.gnome.org/Teams/Design/os-mockups/-/issues/89

**Comment by fthx** [comment]
Hi, thanks for the BR.
I look at this but I've got only one idea.
If it does not work, I'll close this issue since I cannot override Dash natural behavior for this.

**Comment by fthx** [comment]
https://github.com/fthx/dock-from-dash/commit/40f663233dde71b98f488449d82efb2719624643

**Comment by arthurflor23** [comment]
Hi,
just to mention that hover state works in workspace, but the initial problem is in overview mode now.

Thanks again!

**Comment by fthx** [comment]
That's because I now hide the dock in overview because of this:
https://github.com/fthx/dock-from-dash/issues/39

So it's now fixed by:
https://github.com/fthx/dock-from-dash/commit/62a88ab36827533c7bd6f21bfdae7e4b422c80c9
