### ISSUE TITLE
Huge icons

### ISSUE THREAD

**Issue by mi16087** [fthx/dock-from-dash#37]
The icons are huge (64px) with no option to make it smaller (e.g. 32px) which they were before update.
![Screenshot from 2022-04-02 13-56-00](https://user-images.githubusercontent.com/44554049/161382195-41f02414-13b5-47c1-b959-49e9e8ad675a.png)
Also in overview there is, like a shadow, a smaller dock which cannot be interacted with.
![Screenshot from 2022-04-02 13-59-41](https://user-images.githubusercontent.com/44554049/161382285-0c973001-cbd5-4d91-b597-2427c39b6711.png)
I'm useing Fedora 35, gnome 41.5, Wayland

**Comment by fthx** [comment]
I suppose this does the job:
https://github.com/fthx/dock-from-dash/commit/31e1f4f0fecf518d518c603e66b931c18ba7b0d8

Fell free to reopen if it was not the cause.

**Comment by fthx** [comment]
Please note that, normally, the dock has exactly the same size as the dash in overview.

**Comment by julianfairfax** [comment]
> Please note that, normally, the dock has exactly the same size as the dash in overview.

Can this be changed so that the size is not as big?

**Comment by fthx** [comment]
You can change the 15 % ratio (native in GS) in extensions.js.
Maybe I'll include this in a dconf key but not in prefs UI, as this causes inconsistency entering overview, as I told you.
