### ISSUE TITLE
Dock position problem

### ISSUE THREAD

**Issue by mi16087** [fthx/dock-from-dash#38]
When activating dfd extension with "always show the dock" and "show dock in full screen mode" switched off, the position is normal

![Screenshot from 2022-04-05 22-56-31](https://user-images.githubusercontent.com/44554049/161848354-ab0c3e3e-b572-48e2-b7dc-dd4a4fccd3ea.png)

But when activating dfd with  "always show the dock" switched on dock is a little bit upper, and looks broken in overview

![Screenshot from 2022-04-05 22-53-30](https://user-images.githubusercontent.com/44554049/161848781-30da8059-e85d-43e4-87ec-de1e4eb5b26a.png)
![Screenshot from 2022-04-05 22-54-07](https://user-images.githubusercontent.com/44554049/161848808-2835c0df-213e-4314-a28b-7482f4b369d0.png)

And if you then switch on the "show dock in full screen mode" dock is translated all the way down, and overview looks broken

![Screenshot from 2022-04-05 22-54-38](https://user-images.githubusercontent.com/44554049/161849152-ec85f306-6ff6-4ea1-b267-4a5fc8c3550b.png)
![Screenshot from 2022-04-05 22-54-59](https://user-images.githubusercontent.com/44554049/161849170-c96b2a20-cb54-46a9-8fcc-155a3354beba.png)

The position stays bad even if the dfd is switched off and back on if "always show the dock" option is still on.
In sum the position is broken if dfd is activated while the "always show the dock" is turned on, and continues to break til the "always show the dock" is turned off (and back on if preferred while dfd is activated).
Btw I'm on fedora 35, gnome 41.5, wayland.
Also what is "show dock in full screen mode" option supposed to do?

**Comment by fthx** [comment]
https://github.com/fthx/dock-from-dash/commit/8c390db5368f15eee0efd2babff7d70a2b0a7efd

Feel free to reopen if it's not ok.
I tested this, of course! But...

**Comment by fthx** [comment]
It's updated in GS ext website, you should have now a new version.
