### ISSUE TITLE
On Gnome 42 the position of the dock doesn't match with the dash

### ISSUE THREAD

**Issue by Camiropan** [fthx/dock-from-dash#40]
On Gnome 42 the position of the dock doesn't match with the (original) dash. It seems the dock is 24px vertical shifted (position.x - 24).

**Comment by fthx** [comment]
I don't see this, Ubuntu 22.04 GS 42.

Please tell me:
- the **exact** GS 42 version you use
- the distro you use
- the other extensions that are active

**Comment by fthx** [comment]
And please tell me too if the problem is about x or y, that's not clear here:

> dock is 24px vertical shifted (position.x - 24)

**Comment by Camiropan** [comment]
It's about x.

I found the Bug in GNOME OS Nightly without any other extensions installed. So maybe it's a problem only in VMs.

**Comment by fthx** [comment]
and the GS version ?

**Comment by Camiropan** [comment]
GNOME Shell 42.0

**Comment by Camiropan** [comment]
Oh, after a update for Gnome OS the issue is gone!

**Comment by Camiropan** [comment]
Sorry for waste your time

**Comment by fthx** [comment]
That's certainly this:
https://github.com/fthx/dock-from-dash/commit/960ab896a78037bf3882efc942e8255d14cf6c9b
GS did change for beta and again from beta to 42.0.
