### ISSUE TITLE
Please implement intellihide option

### ISSUE THREAD

**Issue by FOOTCLAN** [fthx/dock-from-dash#45]
I know you would like to keep this extension somewhat simple and light but it is so close to what I would consider perfection that I feel compelled to beg you to implement intellihide to compliment the "Always show the dock" option. Please implement this feature so I can finally have the dock I've always wanted.

P.S. I am aware of dash-to-dock. I don't like the way it changes the appearance and position of the dash.

**Comment by fthx** [comment]
https://github.com/fthx/dock-from-dash/issues/43

Maybe for the future but before that I'll do multi-monitors. (A lot of users do full screen display, that makes intellihide not useful, too.)
