### ISSUE TITLE
icon size on dock

### ISSUE THREAD

**Issue by pporkhun** [fthx/dock-from-dash#46]
Is it possible to set size of icons on dock?

**Comment by fthx** [comment]
No because it's handled by GS dash.
BUT if you accept some glitches entering overview, you can play with
`var DASH_MAX_HEIGHT_RATIO = 15;`
(set it to 8-10 eg).
I did that in Dash from Panel extension, you can set the size in prefs UI because there is no overview dash superposition issue here.

**Comment by pporkhun** [comment]
Would You pls tell me where this key I can find?

**Comment by fthx** [comment]
there's no key.
That's in JS code of the extension.

**Comment by pporkhun** [comment]
thks, I found it.
