### ISSUE TITLE
Latest Update Broke Use

### ISSUE THREAD

**Issue by djloubar** [fthx/dock-from-dash#48]
The latest update gave me an _ERROR_ on the installation of it on the latest stable version of Brave; that I downloaded from their official installation guide: https://brave.com/download/
I also tried removing it and reinstalling it with no fix.

Distro: Fedora Linux 36 (Workstation Edition) - beta
DE: GNOME 42.0
Kernel: 5.17.2-300.fc36.x86_64
Shell: bash 5.1.16

**Comment by fthx** [comment]
Sorry I tried this in a Fedora 36 VM and the extension does install & work, at least partially (for auto-hide).
I get no error from logs.

Could you paste here the logs related to "js" and "fthx" ?

**Comment by fthx** [comment]
I close this now because I've got no more info.
Fell free to reopen if you can provide logs.

**Comment by djloubar** [comment]
In the latest boot and update it appears fixed.
I'm assuming it was a odd bug that could have been present or if it was just my pc.
Thank you for testing it tho!
