### ISSUE TITLE
How to change size 

### ISSUE THREAD

**Issue by ducwp** [fthx/dock-from-dash#51]
My laptop resolution: 3200x2000px with scaled 200%, it's too big.

https://i.imgur.com/NtsU2BL.jpg

And the title of "nine dots" icon is "Show  Applicatiions", but when I clicked it, it will show Workspaces.

https://i.imgur.com/V8Dkibp.png

Thanks

**Comment by fthx** [comment]
The dock size is native GS dash size.
Maybe I will make an option in prefs to change that.

The show apps button behaves exactly as GS native one.
