### ISSUE TITLE
Dock doesn't hide when if app launches maximized window

### ISSUE THREAD

**Issue by brainstormtrooper** [fthx/dock-from-dash#52]
When launching an app that starts maximized, the dock stays visible over the bottom of the app window.
It would be nice if the auto-hide feature would take these windows into account as well.
![image](https://user-images.githubusercontent.com/393030/167772719-4752dd7e-2de5-472e-8491-cb32a57f65ec.png)

**Comment by brainstormtrooper** [comment]
Seems that if I move the mouse out of the dock before the window appears it will hide...

**Comment by fthx** [comment]
The reason is the dock is added to UI with addtopchrome but I suppose that when a fullscreen window is created, it takes the top over the dock so the un-hover is not detected.
Sorry but I've got no immediate solution to this. But I've got an idea. Stay tuned.  :-)

**Comment by fthx** [comment]
I cannot reproduce by launching Steam in fullscreen (big picture).
Could you tell me a detailed way to reproduce?
