### ISSUE TITLE
Dock sometimes doesn't auto-hide if there is an opened app in the background.

### ISSUE THREAD

**Issue by Sky1101** [fthx/dock-from-dash#54]
The Dock sometimes gets stuck and doesn't automatically hide after the cursor is moved away from it.
This tends to happen only when there is an opened app right behind the dock.
The dock doesn't seem to get stuck if the desktop is clear with no opened apps on the screen.
The dock doesn't seem to get stuck if a windowed app is on the screen but not right behind it.

Thanks for this awesome lightweight extension, your work is much appreciated! :)

![Screenshot from 2022-05-17 17-30-50](https://user-images.githubusercontent.com/72638937/168825474-518a0101-03a7-4879-8786-0bdd2817ab22.png)

**Comment by fthx** [comment]
If you have a precise way to reproduce, I can have a look.

**Comment by fthx** [comment]
I cannot reproduce.
Feel free to reopen if you can tell me a precise way to reproduce.
