### ISSUE TITLE
Dock is briefly visible, when opening the "About menu"

### ISSUE THREAD

**Issue by Camiropan** [fthx/dock-from-dash#55]
When opening the "About menu" in an application (e.g. in Nautilus) on a non-primary monitor, the Dock is briefly visible.

**Comment by fthx** [comment]
That's strange, I never did experience this.
Do you use any other extension at the same time?

**Comment by Camiropan** [comment]
Yes, but i've disabled all and the issue still exists.



https://user-images.githubusercontent.com/76531567/170831266-aa3fdea4-f81b-48ff-a0c1-f6fff5877681.mp4

The first time the dock appeared I clicked on "about shortwave" in the hamburger menu. The second time I moved the mouse.

**Comment by fthx** [comment]
I have some time now.
I can reproduce.
But I cannot figure out why this happens. The dock is triggered only when hovering the bottom of the screen. Maybe the hover signal is emitted for any reason but I don't see why.
