### ISSUE TITLE
"Error: Invalid work id" spam when an application is activated from the dock

### ISSUE THREAD

**Issue by 1player** [fthx/dock-from-dash#56]
(Migrated from https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5520)

The extension usually works fine, but some time something goes wrong, and every time I click an application in the dock (currently using the Dock from Dash extension but also happens with the regular dock in overview) I get these lines logged:

```
May 24 14:02:24 tranquility gnome-shell[2639]: JS ERROR: Invalid work id 10: Error: Invalid work id 10
                                               queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                               _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
May 24 14:02:24 tranquility gnome-shell[2639]: JS ERROR: Invalid work id 11: Error: Invalid work id 11
                                               queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                               _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
[snip 20 more lines]
```

The application is still activated correctly, but I notice a general sluggishness in the UI when that breaks. Rebooting the system usually fixes it. I'm not sure what's causing it exactly, but I'm pretty sure it's not a gnome-shell bug, as I haven't been able to reproduce when I disable this extension.

OS: Fedora 36 GNOME on Wayland

**Comment by fthx** [comment]
We know this.
We had done some signal handling cleanup. Once Florian told me that GS dash needed to be cleaned up for signals. The GS dash was not thought to be reused!

But afaik this error message does not have any consequence. I usually see 2 lines when I disabled this extension.
Please check all this again and feel free to reopen if you're quite sure that GS sluggishness is related.

**Comment by fthx** [comment]
really solved now.
