### ISSUE TITLE
Light Opacity

### ISSUE THREAD

**Issue by fr0gdude** [fthx/dock-from-dash#63]
New to Linux. I'm running Fedora 36 on GNOME 42. When you are on a white page, the background for the dock is very light and is almost unseeable even on 100% opacity. I suspect adding the ability to change the color to grey would fix this. 
![image](https://user-images.githubusercontent.com/105972849/182122852-c92a7f51-72a5-4e78-9b65-f70387158114.png)

**Comment by fthx** [comment]
You can set the background opacity in extension prefs.

**Comment by fr0gdude** [comment]
Yeah, I changed it to 100% and it is still hard to see the background. I think this needs to be changed with the gnome theme since this dock just uses the default dash.

**Comment by fthx** [comment]
If you change in prefs the dock background opacity then you'll get an dark grey opaque background.
That's 100 % sure.
Except if you have installed an unusual custom theme.
