### ISSUE TITLE
Getting frequent JS Errors in dmesg

### ISSUE THREAD

**Issue by chereskata** [fthx/dock-from-dash#71]
Hello,

i like your extension and use it every day! But i have noticed for some time, that gnome-shell uses an average of 15% CPU on a i7 7600U. After looking into dmesg i found following lines occouring frequently:

`gnome-shell[2298]: JS ERROR: Invalid work id 3: Error: Invalid work id 3
                                             queueDeferredWork@resource:///org/gnome/shell/ui/main.js:874:18
                                             _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
gnome-shell[2298]: JS ERROR: Invalid work id 4: Error: Invalid work id 4
                                             queueDeferredWork@resource:///org/gnome/shell/ui/main.js:874:18
                                             _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
gnome-shell[2298]: JS ERROR: Invalid work id 5: Error: Invalid work id 5
                                             queueDeferredWork@resource:///org/gnome/shell/ui/main.js:874:18
                                             _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
gnome-shell[2298]: JS ERROR: Invalid work id 6: Error: Invalid work id 6
                                             queueDeferredWork@resource:///org/gnome/shell/ui/main.js:874:18
                                             _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
gnome-shell[2298]: JS ERROR: Invalid work id 3: Error: Invalid work id 3
                                             queueDeferredWork@resource:///org/gnome/shell/ui/main.js:874:18
                                             _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
gnome-shell[2298]: JS ERROR: Invalid work id 4: Error: Invalid work id 4
                                             queueDeferredWork@resource:///org/gnome/shell/ui/main.js:874:18
                                             _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
gnome-shell[2298]: JS ERROR: Invalid work id 5: Error: Invalid work id 5
                                             queueDeferredWork@resource:///org/gnome/shell/ui/main.js:874:18
                                             _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
gnome-shell[2298]: JS ERROR: Invalid work id 6: Error: Invalid work id 6
                                             queueDeferredWork@resource:///org/gnome/shell/ui/main.js:874:18
                                             _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
gnome-shell[2298]: JS ERROR: Invalid work id 3: Error: Invalid work id 3
                                             queueDeferredWork@resource:///org/gnome/shell/ui/main.js:874:18
                                             _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
gnome-shell[2298]: JS ERROR: Invalid work id 4: Error: Invalid work id 4
                                             queueDeferredWork@resource:///org/gnome/shell/ui/main.js:874:18
                                             _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
gnome-shell[2298]: JS ERROR: Invalid work id 5: Error: Invalid work id 5
                                             queueDeferredWork@resource:///org/gnome/shell/ui/main.js:874:18
                                             _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
gnome-shell[2298]: JS ERROR: Invalid work id 6: Error: Invalid work id 6
                                             queueDeferredWork@resource:///org/gnome/shell/ui/main.js:874:18
                                             _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14`

I have gnome-shell 43 installed on debian sid

Thanks a lot!

**Comment by chereskata** [comment]
I have got over 90% CPU hogs. Here is a full log:
[cleanlog2.txt](https://github.com/fthx/dock-from-dash/files/9785678/cleanlog2.txt)

**Comment by fthx** [comment]
Yes I do not know how to remove these error messages.
But afaik, there are not a big deal (Florian Muelnner told me it was on GS side, not cleaning signals correctly, because GS Dash was not supposed at first to be used outside its main call!).
I don't believe your CPU usage to be related. Could you check without any other extension?

**Comment by chereskata** [comment]
Hello,

thank you for the fast response. I will try it out for a while. The only other extensions i use are [freon](https://github.com/UshakovVasilii/gnome-shell-extension-freon) and [click-to-close-overview](https://github.com/l3nn4rt/click-to-close-overview)

**Comment by fthx** [comment]
Hi, any update?

**Comment by chereskata** [comment]
Hello,

thank you for your message. I switched to Alpine Linux and i do not get 
any problems with high CPU usage now.

Best Regards

**Comment by fthx** [comment]
I reopen this except for the cpu usage part.
I look at this.

**Comment by fthx** [comment]
happens when opening or closing an app, at least

**Comment by fthx** [comment]
https://github.com/fthx/dock-from-dash/commit/6247f9f5f5c599823e62f1b7be763ce4cd59a084

**Comment by fthx** [comment]
really solved now.
