### ISSUE TITLE
Change Behavior of Clicking on Icon of App with Multiple Open Windows

### ISSUE THREAD

**Issue by Morpheus0x** [fthx/dock-from-dash#72]
Clicking on an icon with more than 2 open windows just shows the activities view. With many open windows, it may be hard to find the actual window of that same application.

I am proposing to add the same or similar behavior that [Dash to Dock](https://extensions.gnome.org/extension/307/dash-to-dock/) has:
Option 1: show a preview of all open windows of that application
![Screenshot from 2022-10-15 15-11-10](https://user-images.githubusercontent.com/22265595/195988793-10f613f7-9b53-460d-9bec-46164ab7a117.png)

Option 2: cycle through all open windows of that application
Option 3a: show the activities overview, but only show windows of that application
Option 3b: show the activities overview, but somehow highlight all the windows of that application

The above screenshot is from Pop!_OS 21.04 with [Cosmic Dock](https://github.com/pop-os/cosmic-dock) replaced with Dash to Dock. Both extensions are basically the same, since Cosmic Dock is a fork of Dash to Dock.

This feature can be optionally enabled from the extension settings. Any one of the four options mentioned above would be fine by me, whatever would be easiest to implement.

**Comment by fthx** [comment]
I'm working on it.
Option 2.

**Comment by fthx** [comment]
https://github.com/fthx/dock-from-dash/commit/6a5df00a764d2efa33d0a0463e393c93ce78fd6d
