### ISSUE TITLE
Animate dock width changes outside of overview

### ISSUE THREAD

**Issue by dgsasha** [fthx/dock-from-dash#76]
When the dock is set to 'always show', there is no animation when the width of the dock changes outside of the overview. I believe it's due to [this line in dash.js](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/dash.js#L796), but I can't think of a good way to change this behavior. It's a fairly minor issue, but I find the lack of an animation slightly jarring, so let me know if you can think of a way to fix it.

**Comment by dgsasha** [comment]
I made some other improvements to how the dock works when it is set to 'always show' over [here](https://github.com/dgsasha/dock-from-dash). I will probably open a pull request for those changes tomorrow. This issue wasn't one I could figure out how to solve though.

**Comment by dgsasha** [comment]
I got this working, although it's kind of an ugly solution. I copied the `_redisplay` method into the Dock class and changed the offending code that blocked animations outside of the overview there. Luckily this method hasn't changed since GNOME 40 so this solution shouldn't cause issues, but it isn't the prettiest solution.

**Comment by fthx** [comment]
I used this trick in dashbar extension...

**Comment by fthx** [comment]
There's no more a 'always show' option.
For that, use DashBar extension that handles this in a better way.
