### ISSUE TITLE
Animation of minimizing windows

### ISSUE THREAD

**Issue by ghabit** [fthx/dock-from-dash#77]
Don't know if it is UI/UX bug or feature request, please edit if you can, but:
Window minimizing animation is moving window to top-left corner, to Activities button.
I think the intended behavior is to move them to dock.

**Comment by fthx** [comment]
That was a request in another BR but there's (again) a lot of code to add and that's not the goal of this extension.
(Intellihide is another thing: this feature is really a feature.)

**Comment by nekohayo** [comment]
For the record, the original ticket is issue #14.
