### ISSUE TITLE
[Bug] Cannot focus application when in overview

### ISSUE THREAD

**Issue by koplo199** [fthx/dock-from-dash#79]
When in overview and clicking on an application icon, dock-from-dash does not focus the application: when there's more than one window opened, nothing is happening (except some kind of hovering effect cycling over the targeted application windows), and when there is one window it actually focus it but minimize it first.

https://user-images.githubusercontent.com/85577251/212162486-d996a7e6-215b-45b3-a6b4-2e853d3fa4d1.mp4

The vanilla behavior is to focus the application (behavior also shared by dash-to-dock): 
 
https://user-images.githubusercontent.com/85577251/212162574-917d2979-190c-4255-96cd-4648d9ac0c59.mp4

It seems the bug is caused by dock-from-dash not differentiating when in overview or not, thus keeping the same behavior when in overview (that is, cycling over windows when windows >=2, and minimizing the window otherwise)

**Comment by fthx** [comment]
Ok that's quite easy to solve.
Just have to check overview state.
But I'll do that after merging some other PR first.
So there's some work before that and I should publish a new version soon, maybe next week.

**Comment by koplo199** [comment]
@fthx Sorry for the delay, but it seems the issue isn't resolved: tested on GNOME 46 using the latest version (`v67`)

**Comment by fthx** [comment]
I realize I forgot that this behaviour is caused by changing the way a dash click is managed to match what we can expect from a dock.

**Comment by fthx** [comment]
But: what window should I focus?

**Comment by fthx** [comment]
https://github.com/fthx/dock-from-dash/commit/41a7321d9a8ccfdf7993b08edf3a5ba27b62df9b

**Comment by fthx** [comment]
Should be ok now?
It's uploaded to GS ext website.

**Comment by koplo199** [comment]
Wow, thanks for the quick fix! I'm not able to test right now however (there's a [bug](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7050) crashing X11 when reloading extensions)
