### ISSUE TITLE
Dock not greyed out when dialog is visible

### ISSUE THREAD

**Issue by dgsasha** [fthx/dock-from-dash#80]
This is a fairly minor issue but it should be an easy fix. When the dock is being shown and a dialog greys out the screen, the dock is not greyed out.
![Screenshot from 2023-01-13 10-40-30](https://user-images.githubusercontent.com/86973360/212359549-f1f6a777-24a9-4a42-bed9-f0cbe478811d.png)

**Comment by dgsasha** [comment]
Added a fix to my pull request, just added one line.

**Comment by fthx** [comment]
The dock hides in this case, focus is lost.
