### ISSUE TITLE
Sometimes does not show up from hiding when GTK animations (reduce animations) are turned off

### ISSUE THREAD

**Issue by nekohayo** [fthx/dock-from-dash#84]
Tested with the Wayland version of GNOME Shell 44.1 on Fedora 38:

If you turn on "Reduce Animation" in the Accessibility settings in GNOME Control Center, and you have a maximized window on the screen (such as the Evolution mail client), it is _sometimes_ impossible to bring the dock up from the bottom of the screen with the mouse, until you force it to show up by pressing `Super` to enter GNOME Shell's overview mode.

Maybe some sort of race condition related to the animations or lack thereof?

**Comment by fthx** [comment]
As far as I tested, I think this is no more an issue since the new code for GS 45 (and new code for showing the dock).
