### ISSUE TITLE
Cannot rearrange order of pinned applications using drag & drop

### ISSUE THREAD

**Issue by nekohayo** [fthx/dock-from-dash#85]
When displaying this dock from the bottom of the screen (unhiding it), it is not possible to use it to drag and drop pinned application launchers to reorder them, whereas it is possible to do so from the original dash in overview mode.

Would it be possible for it to work in the context of this extension as well?

**Comment by fthx** [comment]
https://github.com/fthx/dock-from-dash/commit/8a6fe1f1085d8040bf2902f4e6ad7c4bb2341714
