### ISSUE TITLE
Isolate app in workspace?

### ISSUE THREAD

**Issue by wukongrita** [fthx/dock-from-dash#88]
Hi @fthx, is there a way to show only the app opened in the current workspace when the app icon clicked? (when the setting `include apps from current workspace only` from gnome-control-center is set)

For example:
I have a chrome tab in workspace 1 and have several tabs in workspace 2. So, when I am in the workspace 2 and clicked the chrome icon app from the dock will just show the chrome tabs only from workspace 2 and it won't travel arround to workspace 1.

Thank you

**Comment by fthx** [comment]
I'll make this when I'll make prefs.
Upcoming soon.

**Comment by fthx** [comment]
Set as default behaviour.
Maybe optional when prefs will eventually appear.

https://github.com/fthx/dock-from-dash/commit/67b96da2e81c5fba531bf1c3d0cf8bf0262db151

**Comment by fthx** [comment]
This behaviour is imo better and logical.
