### ISSUE TITLE
Feature request: Icon sizing

### ISSUE THREAD

**Issue by debianmain1** [fthx/dock-from-dash#89]
I'm liking this extension.....I do have a request; I have an ultra-wide & the icon size is about 60px---way too large...it would be very nice to have a smaller size available, like around 32~40px or so.  In any case---Thank you!

**Comment by fthx** [comment]
I'm about to make a new extension based on this one, with no prefs (quite unneeded imo here), for GS 45+.
So, on your wide screen, are the dash icons bigger than GS native dash in overview ?

**Comment by debianmain1** [comment]
To me they look about the same---right around 60px.....Fine for the overview, but way too large for the desktop.  An option to render the icons at .75 or .50 would work very nicely.  Thank you for responding!!!!

**Comment by fthx** [comment]
I won't issue anything like this because the goal is to have a native dash that appears.
BUT you may change var DASH_MAX_HEIGHT_RATIO = 15; to a lower value (8 ? 10 ?) in extension.js .
You can change version in metadata.json to 9999 to avoid any future replacement of extension.js.

**Comment by debianmain1** [comment]
Thank You for the Info....I won't hold you to it, but my eyes will be very grateful.
