### ISSUE TITLE
Show applications button not working after the last update

### ISSUE THREAD

**Issue by Py-GNU-Unix** [fthx/dock-from-dash#9]
If i click the show applications button and i re-click it without moving the mouse out of the dock, the show applications view doesn't close. Note that there is strange flickering while i moved the cursor out of the dock. I didn't have this issue before the last update.

https://user-images.githubusercontent.com/78305798/150382237-7093fab1-6b26-4cd0-a265-a69a61869c39.mp4

P.S. i did set DASH_OPACITY_RATIO = 1 but i don't think it's because of it.

**Comment by fthx** [comment]
Sorry my fault!
The problem is that I decided to let the dock displayed while overview. This is not correct because of your BR.
So:
https://github.com/fthx/dock-from-dash/commit/3da77f467ffeb53bb2e248c5affaa7fea5f98fdf
