### ISSUE TITLE
dock-from-dash are displayed on top of built-in one in overview

### ISSUE THREAD

**Issue by daudix-UFO** [fthx/dock-from-dash#90]
Dock can reveal in overview, which are displayed on top of default one

[Kooha-2023-09-29-20-49-55.webm](https://github.com/fthx/dock-from-dash/assets/77155297/a88f0f97-d88a-4ed4-b79e-76513f03c841)

GNOME 45, extension v65

**Comment by fthx** [comment]
Done.

**Comment by fthx** [comment]
I'm using a new reveal code, forgot to update this part...

**Comment by daudix-UFO** [comment]
Thanks a lot!
