### ISSUE TITLE
Currently not working in Gnome 45

### ISSUE THREAD

**Issue by debianmain1** [fthx/dock-from-dash#91]
I updated to 45 a couple of days ago & updated the extension...It's currently not working in my system & I see this repeated in my logs.

``Oct 10 07:25:39 asus-z690 gnome-shell[2671]: JS ERROR: Invalid work id 3: Error: Invalid work id 3
                                             queueDeferredWork@resource:///org/gnome/shell/ui/main.js:972:18
                                             _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:489:14
                                             @resource:///org/gnome/shell/ui/init.js:21:20

I'm ready to do any checking you need.  Note: This is just after a reboot/user login during gnome-session start.

**Comment by fthx** [comment]
I use GS 45 and it works on my system (Ubuntu 23.10).
This error is "normal" and does not have any consequence, caused by GS not killing signals properly (Florian Muellner told me the native GS dash was not made intially to be used as a "new" object!).

Do you have any other extension installed?
What's the exact version of GS?

**Comment by debianmain1** [comment]
GS is 45.0-1 Arch Linux. I have several extensions installed....Applications Menu, Arch Linux Updates Indicator, Desktop Icons NG (DING), Dock from Dash, Lock Keys, Places Status Indicator, Screenshot Window Sizer, User Themes & GPaste.  I'm thinking that maybe DING is causing a problem.....I installed Dash to Dock to check & it is working, so not sure what is going on......

I can shut off extensions -- leaving Dock on & log out/reboot -- then reenable one at a time to test. Will be doing that later this afternoon...have things to do this morning...

**Comment by debianmain1** [comment]
Hmmmm.....real quickly I disabled all extensions except for Dock & rebooted....It still did not work on login....So it "looks" like its not an extension problem.....

I'll be back in about 4 hours to follow up on this.

**Comment by debianmain1** [comment]
OK---I've restarted with all extensions disabled except for Dock......it is not starting. I uninstalled the extension & then reinstalled it....no start (used gnome extensions website).....this was again after disabling everything else...

I installed dash to dock & it works normally (even though I really don't want to use it)......

Not really sure where to go from here.......Your thoughts?

**Comment by fthx** [comment]
What are the errors in Logs related to "js" search?

**Comment by debianmain1** [comment]
Sorry to not get back before now.  I selected Dock & rebooted....logged in & no bottom dock...went through the logs & the only reference including js is:

gnome-shell[2058]: Execution of main.js threw exception: Module resource:///org/gnome/shell/ui/init.js threw an exception

Don't know if this helps or not.......

**Comment by debianmain1** [comment]
OK...Yes...I'm not sure why also....worked great in 44...nothing in 45.  I'll delete everything & give that a try.

**Comment by debianmain1** [comment]
OK....I removed the extension via the extensions application, checked .local/gnome-shell for a folder, removed the various files from .local/gnome-shell (update-check-45, applications_state & some other cruft)---then rebooted & reinstalled Dock via the Gnome-Extensions website......still nothing.  I'm going to do some more looking/thinking about this one....I'm stumped right now....

**Comment by fthx** [comment]
The big thing with this version (limited prefs will be back when I'll have some time) is the dock reveal code. So do you have a special monitor config?

**Comment by fthx** [comment]
Does Hot Edge (jdoda) extension work for you?

**Comment by debianmain1** [comment]
I do not have a custom config...for my monitor & yes, the Hot Edge extension works for me.....

**Comment by fthx** [comment]
Last thing after that I resign: is this buggy in X11 and Wayland, both?

**Comment by fthx** [comment]
I think to a post of jdoda about a bug in GS45 that has been solved, but I did not experience such a bug that caused his mechanism not to work. Does Arch have some patchs in its GS 45?

**Comment by debianmain1** [comment]
It is buggy in both Wayland & X11.  As for patches....I'll need to check on that...not sure. Won't be able to get back to this for another 5 or so hrs....

**Comment by KardinalReusen** [comment]
I can confirm this bug. I have 3 arch installations and the dock is not working on any of them since Gnome 45.

**Comment by fthx** [comment]
I've just uploaded it again to verify, there's no difference with the (running in Ubuntu 23.10) version I have.
If you have no errors ("JS" or "fthx") in Logs, I'm stuck here.

If you have some (limited) skills in JS, you can include : 
Main.notify("bump");
in some functions (names are clear) of the extension.js code, to know if the dock is triggered, then if the dock display function is executed.

**Comment by KardinalReusen** [comment]
the extension was updated a few minutes ago. No difference.
Sorry I have no programming skills at all.

**Comment by debianmain1** [comment]
> I've just uploaded it again to verify, there's no difference with the (running in Ubuntu 23.10) version I have. If you have no errors ("JS" or "fthx") in Logs, I'm stuck here.
> 
> If you have some (limited) skills in JS, you can include : Main.notify("bump"); in some functions (names are clear) of the extension.js code, to know if the dock is triggered, then if the dock display function is executed.

I'll try this later today to see if I can get you some info......do you want this parted to top of extension or last line?

**Comment by fthx** [comment]
This way I will know if the signal that is sent to the dock is activated (pressure on bottom of the screen, first part of the code, that emits this signal that the dock listens to).

**Comment by fthx** [comment]
Could you try this?
- alt+F2 (execute)
- execute `lg` (looking glass of GNOME Shell)
- enter: `Main.overview.shouldToggleByCornerOrButton()`
- give me the result (boolean)

**Comment by debianmain1** [comment]
Answer is r(0) = true

**Comment by debianmain1** [comment]
I have "hacked" the extension...what is the output you want?

**Comment by fthx** [comment]
Do you have a notification when you hover the bottom of your screen?

**Comment by debianmain1** [comment]
YES...I get the "bump" in notifications & the Dock appears...as soon as I mouse away...the Dock is gone.

**Comment by fthx** [comment]
so there never was any issue here... that's the way this dock works.

**Comment by debianmain1** [comment]
Hmmm....is there a way to have the dock visible at all times unless a window overlapped like it was before 45?

**Comment by fthx** [comment]
It never had intelligent hide.
