### ISSUE TITLE
Mouse leaving bottom hot edge does not close dock in GNOME 45

### ISSUE THREAD

**Issue by trevnels** [fthx/dock-from-dash#92]
After updating to GNOME 45, I've noticed that the dock can get stuck open in some cases:
1. Moving the mouse to the bottom left or bottom right of the screen to open the dock, then moving the mouse directly upwards, not touching the dock in the process.
2. Moving the mouse to the bottom of a secondary display.

Both of these cases will open the dock, but it will be stuck open until the cursor is moved in and out of the dock itself - it seems like moving the cursor away from the bottom hot edge of the screen does not hide the dock like it used to.

**Comment by trevnels** [comment]
Looking at the code it seems like the bottom hot edge will toggle the state of the dock, but because the delay for automatically hiding the dock is no longer present, it seems like the dock is stuck open. Activating the hot edge again will close the dock.

**Comment by fthx** [comment]
It's complicated since focus that makes the timeout inactive is lost in some cases with recent versions of GS. And here I tried to make the reordering of app icons possible.

**Comment by fthx** [comment]
It's solved but I wait a little bit to release some other changes.

**Comment by fthx** [comment]
https://github.com/fthx/dock-from-dash/commit/e6fe82cbcdb059bf9a147f3857799d13d2fb6684
