### ISSUE TITLE
Existing shown icons sometimes suddenly disappear / stop showing

### ISSUE THREAD

**Issue by nekohayo** [fthx/dock-from-dash#97]
Sometimes, existing favorited and "already launched" applications' icons disappear, but their slot and dots remain, and they are still interactive. When launching a new non-favorited application in that state, its icon appears normally, as you can see in that screenshot with the Kooha and GNOME Settings icons appearing:

![Screenshot from 2024-03-09 11-43-43](https://github.com/fthx/dock-from-dash/assets/479401/de5b78b1-25bc-4b14-a177-13ffc4ae447f)

I am unsure when and how this happens (I'm not even suspending/resuming my computer or reloading the extension, or doing particular actions), it just randomly happens "sometimes" after a while, with GNOME Shell 45.4 running on Wayland on Fedora 39.

_In addition_ to the regular invalid work ID errors seen in #93 in `journalctl`, in this specific case it seems there _also_ are some slightly different, more detailed errors:

```
gnome-shell[3339]: Invalid work id 22: Error: Invalid work id 22

Stack trace:
  queueDeferredWork@resource:///org/gnome/shell/ui/main.js:985:18
  _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:489:14
  _callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
  _emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
  _onFavsChanged@resource:///org/gnome/shell/ui/appFavorites.js:87:14
  createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:730:46
  _addFavorite@resource:///org/gnome/shell/ui/appFavorites.js:157:25
  addFavoriteAtPos@resource:///org/gnome/shell/ui/appFavorites.js:162:19
  addFavorite@resource:///org/gnome/shell/ui/appFavorites.js:175:14
  AppMenu/this._toggleFavoriteItem<@resource:///org/gnome/shell/ui/appMenu.js:81:36
  addAction/<@resource:///org/gnome/shell/ui/popupMenu.js:569:21
  activate@resource:///org/gnome/shell/ui/popupMenu.js:194:14
  _init/<@resource:///org/gnome/shell/ui/popupMenu.js:111:24
  @resource:///org/gnome/shell/ui/init.js:21:20
```

**Comment by nekohayo** [comment]
Also, when this happens: if you press the `Super` key, the icons in the Overview's dash are fine; it's just this extension's icons that disappear.

**Comment by fthx** [comment]
Hi, I never experienced this.
I've no idea what's happening here.
