### ISSUE TITLE
Support GNOME 46

### ISSUE THREAD

**Issue by BuZZ-dEE** [fthx/dock-from-dash#98]
Please support for GNOME 46.

**Comment by fthx** [comment]
Soon, once Ubuntu 24.04 has GS 46...

**Comment by BuZZ-dEE** [comment]
I use Arch and I want it now. 😋

**Comment by neblogas** [comment]
BTW I use Arch...

**Comment by fthx** [comment]
Yep but I do use Ubuntu 24.04.
And I do not have the time to install a GS 46 VM.

Ubuntu 24.04 has landed GS 46 but all is stuck in t64 transition. A couple of days to wait for.

**Comment by fthx** [comment]
I don't want to publish untested extensions.

**Comment by juxuanu** [comment]
To test extensions ahead of time, Gnome publishes  https://os.gnome.org/ which you can download directly from within https://flathub.org/apps/org.gnome.Boxes. Really easy and fast, so you can test the extension :-)

**Comment by fthx** [comment]
Yes that's a VM.
;-)

**Comment by fthx** [comment]
https://github.com/fthx/dock-from-dash/commit/e6fe82cbcdb059bf9a147f3857799d13d2fb6684
